# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 947cdf6a72db36b86a800ff44555a24e348dd975264ce0f84044c98306b08cebf6f7710e243f5044ab4fd99585b3d71bc95fdaeff03d1293c7ea0f3a69c45a81

test:
  secret_key_base: 16b0d559c0485f7df8e79abd8d10edcd2863bcac5e86cb009987b71e2a1dbbf4fa4221832f91ba5999b4ede0634c8e94a9b40492d7998d693fe436a871204f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
